`timescale 1ns / 1ps

// Compares the RTL against deterministic vectors generated by the independent
// Python reference model. Override NUM_VECTORS when generating a different
// number of vectors.
module tb_software_vectors #(
    parameter integer NUM_VECTORS = 256,
    parameter integer DATA_W = 8,
    parameter integer TILE_ELEMS = 16,
    parameter integer MAX_OUT_BITS = 200
);
    logic [TILE_ELEMS-1:0][DATA_W-1:0] tile_in;
    logic [$clog2(TILE_ELEMS+1)-1:0] nonzero_count;
    logic [$clog2(TILE_ELEMS+1)-1:0] zero_count;
    logic [7:0] raw_cost, bitmap_cost, rle_cost, selected_cost;
    logic [1:0] format_select;

    logic [MAX_OUT_BITS-1:0] raw_data, bitmap_data, rle_data;
    logic [7:0] raw_len, bitmap_len, rle_len;

    logic [TILE_ELEMS-1:0][DATA_W-1:0] raw_tile_out;
    logic [TILE_ELEMS-1:0][DATA_W-1:0] bitmap_tile_out;
    logic [TILE_ELEMS-1:0][DATA_W-1:0] rle_tile_out;
    logic raw_decode_valid, bitmap_decode_valid, rle_decode_valid;

    logic [DATA_W*TILE_ELEMS-1:0] tile_mem [0:NUM_VECTORS-1];
    logic [25:0] expected_mem [0:NUM_VECTORS-1];
    logic [MAX_OUT_BITS-1:0] raw_mem [0:NUM_VECTORS-1];
    logic [MAX_OUT_BITS-1:0] bitmap_mem [0:NUM_VECTORS-1];
    logic [MAX_OUT_BITS-1:0] rle_mem [0:NUM_VECTORS-1];

    string vector_dir;

    adaptive_selector u_selector (
        .tile_in(tile_in),
        .nonzero_count(nonzero_count),
        .zero_count(zero_count),
        .raw_cost(raw_cost),
        .bitmap_cost(bitmap_cost),
        .rle_cost(rle_cost),
        .format_select(format_select),
        .selected_cost(selected_cost)
    );

    raw_encoder u_raw (
        .tile_in(tile_in), .data_out(raw_data), .len_out(raw_len)
    );
    bitmap_encoder u_bitmap (
        .tile_in(tile_in), .data_out(bitmap_data), .len_out(bitmap_len)
    );
    rle_encoder u_rle (
        .tile_in(tile_in), .data_out(rle_data), .len_out(rle_len)
    );

    decompressor u_raw_decoder (
        .data_in(raw_data),
        .len_in(raw_len),
        .tile_out(raw_tile_out),
        .valid(raw_decode_valid)
    );
    decompressor u_bitmap_decoder (
        .data_in(bitmap_data),
        .len_in(bitmap_len),
        .tile_out(bitmap_tile_out),
        .valid(bitmap_decode_valid)
    );
    decompressor u_rle_decoder (
        .data_in(rle_data),
        .len_in(rle_len),
        .tile_out(rle_tile_out),
        .valid(rle_decode_valid)
    );

    initial begin
        if (!$value$plusargs("VECTOR_DIR=%s", vector_dir))
            vector_dir = "generated_vectors";

        $readmemh({vector_dir, "/tiles.mem"}, tile_mem);
        $readmemh({vector_dir, "/expected.mem"}, expected_mem);
        $readmemh({vector_dir, "/raw.mem"}, raw_mem);
        $readmemh({vector_dir, "/bitmap.mem"}, bitmap_mem);
        $readmemh({vector_dir, "/rle.mem"}, rle_mem);

        for (integer i = 0; i < NUM_VECTORS; i++) begin
            tile_in = tile_mem[i];
            #1;

            assert (raw_cost == expected_mem[i][7:0])
                else $fatal(1, "RAW cost mismatch at vector %0d", i);
            assert (bitmap_cost == expected_mem[i][15:8])
                else $fatal(1, "Bitmap cost mismatch at vector %0d", i);
            assert (rle_cost == expected_mem[i][23:16])
                else $fatal(1, "RLE cost mismatch at vector %0d", i);
            assert (format_select == expected_mem[i][25:24])
                else $fatal(1, "Format selection mismatch at vector %0d", i);

            assert (selected_cost ==
                    ((format_select == 2'b00) ? raw_cost :
                     (format_select == 2'b01) ? bitmap_cost : rle_cost))
                else $fatal(1, "Selected cost mismatch at vector %0d", i);

            assert (raw_len == raw_cost && raw_data == raw_mem[i])
                else $fatal(1, "RAW payload mismatch at vector %0d", i);
            assert (bitmap_len == bitmap_cost && bitmap_data == bitmap_mem[i])
                else $fatal(1, "Bitmap payload mismatch at vector %0d", i);
            assert (rle_len == rle_cost && rle_data == rle_mem[i])
                else $fatal(1, "RLE payload mismatch at vector %0d", i);

            assert (raw_decode_valid && raw_tile_out == tile_in)
                else $fatal(1, "RAW decoder round-trip mismatch at vector %0d", i);
            assert (bitmap_decode_valid && bitmap_tile_out == tile_in)
                else $fatal(1, "Bitmap decoder round-trip mismatch at vector %0d", i);
            assert (rle_decode_valid && rle_tile_out == tile_in)
                else $fatal(1, "RLE decoder round-trip mismatch at vector %0d", i);
        end

        $display("PASS: %0d Python-oracle vectors matched the RTL and decompressed correctly.",
                 NUM_VECTORS);
        $finish;
    end
endmodule
